version: '3'

services:
  # docker run --net=nginx-practice-network -t --name=ubuntu ubuntu
  ubuntu:
    image: ubuntu
    networks:
      - nginx-practice-network
    tty: true

  # docker run --net=nginx-practice-network -v `pwd`/nginx-frontend/html:/usr/share/nginx/html:ro -v `pwd`/nginx-frontend/conf.d:/etc/nginx/conf.d/:ro --name=nginx-frontend nginx
  nginx-frontend:
    image: nginx
    networks:
      - nginx-practice-network
    volumes:
      - ./nginx-frontend/html:/usr/share/nginx/html:ro
      - ./nginx-frontend/conf.d:/etc/nginx/conf.d/:ro
    ports:
      - 80:80

  # docker run --net=nginx-practice-network -v `pwd`/nginx-backend1/html:/usr/share/nginx/html:ro --name=nginx-backend1 nginx
  nginx-backend1:
    image: nginx
    networks:
      - nginx-practice-network
    volumes:
      - ./nginx-backend1/html:/usr/share/nginx/html:ro

  # docker run --net=nginx-practice-network -v `pwd`/nginx-backend2/html:/usr/share/nginx/html:ro --name=nginx-backend2 nginx
  nginx-backend2:
    image: nginx
    networks:
      - nginx-practice-network
    volumes:
      - ./nginx-backend2/html:/usr/share/nginx/html:ro

  # docker run --net=nginx-practice-network -v `pwd`/nginx-backend3/html:/usr/share/nginx/html:ro --name=nginx-backend3 nginx
  nginx-backend3:
    image: nginx
    networks:
      - nginx-practice-network
    volumes:
      - ./nginx-backend3/html:/usr/share/nginx/html:ro

  # docker run --net=nginx-practice-network -v `pwd`/nginx-backend4/html:/usr/share/nginx/html:ro --name=nginx-backend4 nginx
  nginx-backend4:
    image: nginx
    networks:
      - nginx-practice-network
    volumes:
      - ./nginx-backend4/html:/usr/share/nginx/html:ro

networks:
  # docker network create nginx-practice-network
  # 実際はComposeの仕様で`{親ディレクトリ名}-nginx-practice-network`という名前になる
  nginx-practice-network:
    driver: bridge
